### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by blindguydiy** [kshitizrimal/Cash-Recognition-Android#3]
I am blind am developing also a AI. I need to show someone example of a dataset to take image of South African rand to train.  But not finding any realtime examples of a image dataset to train.  The link to this dataset is not working and I want to ask if I can use the image dataset to show how the images must look that they can take South African banknotes images.  Do you have a link to your dataset I can use to have a idee how the dataset images must look like?  Thank you.  I know it is not a issue but struggle to find a contact email.  My email is blindguydiy@gmail.com. Hendrik from South Africa

**Comment by kshitizrimal** [comment]
Hi, you can visit this link for Datasets and more information on how to train the model using it.

http://ainepal.org/public-release-of-cash-recognition-for-visually-impaired/

**Comment by blindguydiy** [comment]
Thank you. Sent from Mail for Windows 10 From: kshitizrimalSent: Thursday, 18 March 2021 18:33To: kshitizrimal/Cash-Recognition-AndroidCc: blindguydiy; AuthorSubject: Re: [kshitizrimal/Cash-Recognition-Android] Dataset (#3) Closed #3.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
